Fusion 08 update
wapopartners/Fusion-Training-User-Stories pull request #14
Opened 2020-08-28 19:07 UTC by omonoukpoma

2020-09-01 21:12 UTC, nicrocs requested changes
Just a couple of quick additions to link to the docs for some context. Otherwise look good!

2020-09-01 21:12 UTC, nicrocs commented on README.md
> +5. Now, we need to fetch the content using Fusion's `useContent`. Import `useContent` from Fusion:
Adding a link to the ALC docs could be helpful to provide context. https://redirector.arcpublishing.com/alc/arc-products/pagebuilder/fusion/documentation/recipes/fetching-content-with-hooks.md

2020-09-01 21:12 UTC, nicrocs commented on README.md
> +2. Add a PageBuilder custom field that enables the user to select our article content source:
Adding a link to the ALC docs here should help provide context to the `contentConfig` proptype https://redirector.arcpublishing.com/alc/arc-products/pagebuilder/fusion/documentation/recipes/dynamically-configuring-content-with-hooks.md

2020-09-03 18:21 UTC, omonoukpoma commented
@nicrocs links have been added in

2020-09-04 15:02 UTC, nicrocs approved these changes

2020-09-08 15:27 UTC, merged