Fusion 12 update
wapopartners/Fusion-Training-User-Stories pull request #18
Opened 2020-09-08 16:46 UTC by omonoukpoma

2020-09-09 16:40 UTC, omonoukpoma commented
this is on hold pending fusion-11-update merge

2020-09-09 22:18 UTC, nicrocs requested changes
Looks good. I think there are a couple of missing words, but otherwise was able to follow along no problem.

2020-09-09 22:18 UTC, nicrocs commented on README.md
> +2. In this file, create a functional component that all children within the props like so:
Is there a missing word here? `Renders` all children?

2020-09-09 22:18 UTC, nicrocs commented on README.md
> +5. Iterate through the `children` props and each item in a div with the desktopCols, tabletCols and mobileCols values provided by the editor (using bootstrap)
Should this be something like `place each item in a div`

2020-09-10 20:42 UTC, nicrocs approved these changes
👍

2020-09-10 20:45 UTC, merged