Fusion 03 update
wapopartners/Fusion-Training-User-Stories pull request #6
Opened 2020-08-20 18:57 UTC by omonoukpoma

2020-08-21 22:37 UTC, ghost requested changes

2020-08-21 22:37 UTC, ghost commented on README.md
> +```
We should probably have more steps here that walk them through adding this feature to a page in pagebuilder? Otherwise they have no way to preview the code their wrote.

2020-08-25 13:56 UTC, omonoukpoma commented on README.md
> +```
@nealmalkaniwapo done

2020-08-25 17:40 UTC, nicrocs approved these changes
Works for me! 👍

2020-08-25 18:00 UTC, merged